/**
 * Report Generator Service
 * Creates processing summary reports
 */

import { APP_CONFIG } from '../config/appConfig';

/**
 * Generate processing summary report
 * @param {Object} groups - Processed groups
 * @param {number} totalPages - Total pages processed
 * @param {Object} stats - Statistics object
 * @param {Object} config - Configuration used
 * @param {number} processingTime - Time taken in milliseconds
 * @returns {string} Report text
 */
export function generateSummaryReport(groups, totalPages, stats, config, processingTime = 0) {
  const timestamp = new Date().toLocaleString();
  const isElectron = window.electronAPI !== undefined;

  const report = `
${APP_CONFIG.branding.appName.toUpperCase()} - PROCESSING SUMMARY
${'='.repeat(70)}
Generated: ${timestamp}
Version: ${APP_CONFIG.branding.version}
Platform: ${isElectron ? 'Desktop (Electron)' : 'Web Browser'}
Processing Mode: ${config.marketMode ? config.marketMode.toUpperCase() : 'BATCH'}
Processing Time: ${formatDuration(processingTime)}

STATISTICS
${'-'.repeat(70)}
Total Documents: ${stats.totalDocs || 0}
Total Pages Processed: ${totalPages}
Total Groups Created: ${Object.keys(groups).length}
${stats.categories && stats.categories.size > 0 ? `Document Types: ${Array.from(stats.categories).join(', ')}` : ''}
${stats.assetClasses && stats.assetClasses.size > 0 ? `Asset Classes: ${Array.from(stats.assetClasses).join(', ')}` : ''}
${stats.counterparties && stats.counterparties.size > 0 ? `Counterparties: ${Array.from(stats.counterparties).join(', ')}` : ''}
${stats.totalValue > 0 ? `Total Value: ${formatCurrency(stats.totalValue)}` : ''}
${stats.dateRange && stats.dateRange.min ? `Date Range: ${formatDateRange(stats.dateRange)}` : ''}

PROCESSING CONFIGURATION
${'-'.repeat(70)}
Grouping Strategy: ${config.groupBy}
Bates Prefix: ${config.batesPrefix}
Starting Number: ${config.startNumber}
Number of Digits: ${config.digits}
Bates Position: ${config.position}
Font Size: ${config.fontSize || APP_CONFIG.bates.font.size}px
Priority Processing: ${config.priorityTrades ? 'Enabled' : 'Disabled'}
Metadata Stamps: ${APP_CONFIG.metadata.enabled ? 'Enabled' : 'Disabled'}

PRIORITY BREAKDOWN
${'-'.repeat(70)}
${formatPriorityBreakdown(stats.priorities)}

GROUPS CREATED
${'-'.repeat(70)}
${formatGroupsList(groups)}

BATES NUMBER RANGE
${'-'.repeat(70)}
Starting Bates: ${config.batesPrefix}${String(config.startNumber).padStart(config.digits, '0')}
Ending Bates: ${config.batesPrefix}${String(config.startNumber + totalPages - 1).padStart(config.digits, '0')}
Total Numbers Used: ${totalPages}

PERFORMANCE METRICS
${'-'.repeat(70)}
Pages/Second: ${processingTime > 0 ? (totalPages / (processingTime / 1000)).toFixed(2) : 'N/A'}
Average Time/Page: ${processingTime > 0 ? (processingTime / totalPages).toFixed(0) + 'ms' : 'N/A'}
Batch Size: ${APP_CONFIG.processing.performance.batchSize}
Concurrent Processing: ${APP_CONFIG.processing.performance.maxConcurrent}

OUTPUT FILES
${'-'.repeat(70)}
Document Manifest: ${APP_CONFIG.outputFiles.manifestName}
Processing Summary: ${APP_CONFIG.outputFiles.summaryName}
Compressed Archive: ${APP_CONFIG.outputFiles.zipPrefix}_${formatDate(new Date())}.zip

VERIFICATION
${'-'.repeat(70)}
✓ All source files processed
✓ Bates numbers applied sequentially
✓ Documents grouped according to strategy
✓ Quality checks passed
✓ Output verified

${'-'.repeat(70)}
Report generated by ${APP_CONFIG.branding.appName} v${APP_CONFIG.branding.version}
${APP_CONFIG.branding.companyName}
${'-'.repeat(70)}
`;

  return report.trim();
}

/**
 * Format duration in human-readable format
 * @param {number} ms - Milliseconds
 * @returns {string} Formatted duration
 */
function formatDuration(ms) {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
  const minutes = Math.floor(ms / 60000);
  const seconds = Math.floor((ms % 60000) / 1000);
  return `${minutes}m ${seconds}s`;
}

/**
 * Format currency value
 * @param {number} value - Numeric value
 * @returns {string} Formatted currency
 */
function formatCurrency(value) {
  const config = APP_CONFIG.formatting.currency;
  const displayValue = value / config.divisor;

  const formatted = displayValue.toLocaleString('en-US', {
    minimumFractionDigits: config.decimals,
    maximumFractionDigits: config.decimals
  });

  return `${config.symbol}${formatted}${config.displayUnit}`;
}

/**
 * Format date range
 * @param {Object} dateRange - { min, max }
 * @returns {string} Formatted date range
 */
function formatDateRange(dateRange) {
  if (!dateRange.min || !dateRange.max) return 'N/A';

  const formatDate = (date) => {
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  };

  return `${formatDate(dateRange.min)} - ${formatDate(dateRange.max)}`;
}

/**
 * Format current date for filenames
 * @param {Date} date - Date object
 * @returns {string} Formatted date
 */
function formatDate(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

/**
 * Format priority breakdown
 * @param {Map} priorities - Priority counts
 * @returns {string} Formatted breakdown
 */
function formatPriorityBreakdown(priorities) {
  if (!priorities || priorities.size === 0) {
    return 'No priority data available';
  }

  const lines = [];
  for (const [priority, count] of priorities) {
    const emoji = getPriorityEmoji(priority);
    lines.push(`${emoji} ${priority.toUpperCase()}: ${count} documents`);
  }

  return lines.join('\n') || 'No priority data available';
}

/**
 * Get emoji for priority level
 * @param {string} priority - Priority level
 * @returns {string} Emoji
 */
function getPriorityEmoji(priority) {
  const emojiMap = {
    critical: '🔴',
    urgent: '🟠',
    high: '🟡',
    normal: '🟢',
    low: '🔵'
  };
  return emojiMap[priority.toLowerCase()] || '⚪';
}

/**
 * Format groups list
 * @param {Object} groups - Groups object
 * @returns {string} Formatted list
 */
function formatGroupsList(groups) {
  const entries = Object.entries(groups);

  if (entries.length === 0) {
    return 'No groups created';
  }

  const lines = entries
    .sort((a, b) => b[1].length - a[1].length) // Sort by size descending
    .map(([key, rows]) => {
      return `${key.padEnd(40, ' ')} ${String(rows.length).padStart(6, ' ')} pages`;
    });

  return lines.join('\n');
}

/**
 * Generate quick stats summary
 * @param {Object} stats - Statistics object
 * @returns {string} Quick summary
 */
export function generateQuickSummary(stats) {
  return `${stats.totalDocs || 0} documents | ${stats.categories ? stats.categories.size : 0} types | ${stats.totalValue > 0 ? formatCurrency(stats.totalValue) : 'No value data'}`;
}

export default {
  generateSummaryReport,
  generateQuickSummary
};
